/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package control;

import javax.swing.JOptionPane;

/**
 *
 * @author Marco
 */
public class FilmesForm extends javax.swing.JFrame {

    private String[] nomes = {
            "Lucas Almeida", 
            "Mariana Costa", 
            "Rafael Pereira", 
            "Ana Silva", 
            "Bruno Oliveira", 
            "Carolina Santos", 
            "Diego Martins", 
            "Fernanda Rocha", 
            "Guilherme Souza", 
            "Júlia Mendes"
        };
    
    public FilmesForm() {
        initComponents();
        
        MeuCliente cliente = new MeuCliente();
        
        lblID.setText(cliente.getNomeDNS());
        
        String nomeSelecionado = (String) JOptionPane.showInputDialog(
            null, 
            "Selecione um nome:", 
            "Lista de Nomes", 
            JOptionPane.QUESTION_MESSAGE, 
            null, 
            nomes, 
            nomes[0]
        );

        if (nomeSelecionado != null) {
            JOptionPane.showMessageDialog(null, "Você selecionou: " + nomeSelecionado);
        }
        
        lblServidor.setText(nomeSelecionado);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblID = new javax.swing.JTextField();
        lblServidor = new javax.swing.JTextField();
        cbFilmes = new javax.swing.JComboBox<>();
        spinNota = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btnInfo = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        cbOpiton = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Servidor");

        jLabel2.setText("Filme :");

        cbFilmes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escolha o filme", "O Poderoso Chefão", "Clube da Luta", "Pulp Fiction: Tempo de Violência", "A Origem", "O Senhor dos Anéis: A Sociedade do Anel", "Matrix", "O Silêncio dos Inocentes", "Forrest Gump: O Contador de Histórias", "A Vida é Bela", "O Resgate do Soldado Ryan", "Gladiador", "O Rei Leão", "Vingadores: Ultimato", "Jurassic Park: Parque dos Dinossauros", "Star Wars: O Império Contra-Ataca", "Interestelar", "Corra!", "A Forma da Água", "Cidadão Kane", "Parasita" }));

        spinNota.setModel(new javax.swing.SpinnerNumberModel(0, 0, 3, 1));
        spinNota.setName(""); // NOI18N
        spinNota.setRequestFocusEnabled(false);

        jLabel3.setText("ID");

        jLabel4.setText("Nota :");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        btnInfo.setText("?");
        btnInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfoActionPerformed(evt);
            }
        });

        jButton1.setText("Execultar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setText("Opções :");

        cbOpiton.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Requisitar filme não avaliado", "Avaliar Filme", "Recomendar filme", "Filmes Avaliados por mim" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblID, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(spinNota, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnInfo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbOpiton, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(cbFilmes, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblServidor))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblServidor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbFilmes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spinNota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(btnInfo)
                    .addComponent(jLabel5)
                    .addComponent(cbOpiton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfoActionPerformed
        JOptionPane.showMessageDialog(null,"Valores a serem usados: \n1 = ruim\n 2 = bom\n 3 = ótimo\n");
    }//GEN-LAST:event_btnInfoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int filmeInd = cbFilmes.getSelectedIndex();
        int nota = Integer.parseInt(spinNota.getValue().toString());
        int op = cbOpiton.getSelectedIndex();
        
        String msg = null;
        
        if(filmeInd == 0){
            JOptionPane.showMessageDialog(null, "Favor informar o FILME a ser avaliado");
            cbFilmes.requestFocus();
        }else{
            String nomeFilme = cbFilmes.getSelectedItem().toString();
            msg = lblServidor.getText() + " avaliou o filme '" + nomeFilme + "' com " + nota ;
        }
        
        MeuCliente cli = new MeuCliente();
        msg = msg 
                + ";"+ (filmeInd - 1) 
                + ";" + clienteIndex(lblServidor.getText()) 
                + ";" + nota
                + ";" + op;
        
        String resposta = cli.enviarMsg(msg);
        
         jTextArea1.setText(resposta);
    }//GEN-LAST:event_jButton1ActionPerformed
   
    private int clienteIndex(String cli){
        String[] nomes = {"Lucas Almeida"
                , "Mariana Costa"
                , "Rafael Pereira"
                , "Ana Silva"
                , "Bruno Oliveira"
                , "Carolina Santos"
                , "Diego Martins"
                , "Fernanda Rocha"
                , "Guilherme Souza"
                , "Júlia Mendes"};
        
        
        for(int i = 0; i< 10;i++){
            if(cli.equals(nomes[i])){
                return i;
            }
        }
        return 0;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FilmesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FilmesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FilmesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FilmesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FilmesForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInfo;
    private javax.swing.JComboBox<String> cbFilmes;
    private javax.swing.JComboBox<String> cbOpiton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField lblID;
    private javax.swing.JTextField lblServidor;
    private javax.swing.JSpinner spinNota;
    // End of variables declaration//GEN-END:variables
}
